[package]
name = "running-mate"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
mongodb = "0.9.0"
bson = "0.14.0"
serde_json = "1.0.44"
log = "0.4.8"
simplelog = "0.7.4"
