#!/usr/bin/env bash

# This is only relevant to my specific development workflow. It rsyncs the code
# to the remote machine which receives the webhook requests from Telegram and
# builds it.

rsync -a --progress --delete \
    --exclude=.git --exclude=target \
    . chatbot:running-mate/
ssh chatbot "cd running-mate/ && docker-compose up --build -d"
